repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      # linter — with auto-fix
      - id: ruff
        args: ["--fix"]
      # formatter
      - id: ruff-format
 